<#
.SYNOPSIS
    Runs Playwright E2E tests and creates GitHub issues for any failures.

.DESCRIPTION
    1. Runs 'dotnet test' with TRX logger
    2. Parses the TRX XML for failed tests
    3. For each failure, creates a GitHub issue (if one doesn't already exist)
    4. Prints a summary

.PARAMETER Filter
    Optional test filter expression (e.g., "Category!=RequiresModel")

.PARAMETER DryRun
    If specified, prints what issues would be created without actually creating them.

.EXAMPLE
    .\create-issues-from-failures.ps1
    .\create-issues-from-failures.ps1 -Filter "Category!=RequiresModel"
    .\create-issues-from-failures.ps1 -DryRun
#>
param(
    [string]$Filter = "",
    [switch]$DryRun
)

$ErrorActionPreference = "Continue"
$projectDir = Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
# If run from repo root, adjust
if (-not (Test-Path "$projectDir\OpenClawNet.PlaywrightTests.csproj")) {
    $projectDir = Join-Path $PSScriptRoot ".."
}

$resultsDir = Join-Path $projectDir "TestResults"
$trxFile = Join-Path $resultsDir "results.trx"

# Clean previous results
if (Test-Path $resultsDir) {
    Remove-Item -Recurse -Force $resultsDir
}

Write-Host "========================================" -ForegroundColor Cyan
Write-Host " Running Playwright E2E Tests" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan

# Build the test command
$testCmd = "dotnet test `"$projectDir`" --logger `"trx;LogFileName=results.trx`" --results-directory `"$resultsDir`""
if ($Filter) {
    $testCmd += " --filter `"$Filter`""
}

Write-Host "Command: $testCmd" -ForegroundColor DarkGray
Invoke-Expression $testCmd

# Check if TRX file was created
if (-not (Test-Path $trxFile)) {
    Write-Host "`nERROR: TRX file not found at $trxFile" -ForegroundColor Red
    Write-Host "Tests may not have run. Check build errors above." -ForegroundColor Yellow
    exit 1
}

# Parse TRX file
Write-Host "`n========================================" -ForegroundColor Cyan
Write-Host " Parsing Test Results" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan

[xml]$trx = Get-Content $trxFile
$ns = @{ t = "http://microsoft.com/schemas/VisualStudio/TeamTest/2010" }

$results = Select-Xml -Xml $trx -XPath "//t:UnitTestResult" -Namespace $ns
$failures = @()

foreach ($result in $results) {
    $node = $result.Node
    if ($node.outcome -eq "Failed") {
        $testName = $node.testName
        $errorMessage = ""
        $stackTrace = ""

        $output = $node.Output
        if ($output) {
            $errorInfo = $output.ErrorInfo
            if ($errorInfo) {
                $errorMessage = $errorInfo.Message
                $stackTrace = $errorInfo.StackTrace
            }
        }

        $failures += @{
            TestName     = $testName
            ClassName    = ($testName -split '\.')[0..($testName.Split('.').Count - 2)] -join '.'
            MethodName   = ($testName -split '\.')[-1]
            ErrorMessage = $errorMessage
            StackTrace   = $stackTrace
            Duration     = $node.duration
        }
    }
}

$totalTests = ($results | Measure-Object).Count
$failedCount = $failures.Count
$passedCount = $totalTests - $failedCount

Write-Host "Total: $totalTests | Passed: $passedCount | Failed: $failedCount" -ForegroundColor $(if ($failedCount -gt 0) { "Yellow" } else { "Green" })

if ($failedCount -eq 0) {
    Write-Host "`nAll tests passed! No issues to create." -ForegroundColor Green
    exit 0
}

# Create GitHub issues for failures
Write-Host "`n========================================" -ForegroundColor Cyan
Write-Host " Creating GitHub Issues for Failures" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan

$createdCount = 0
$skippedCount = 0

foreach ($failure in $failures) {
    $issueTitle = "[E2E Failure] $($failure.TestName)"

    # Check if issue already exists
    $existing = gh issue list --search "$issueTitle" --state open --json title 2>$null | ConvertFrom-Json
    if ($existing -and ($existing | Where-Object { $_.title -eq $issueTitle })) {
        Write-Host "  SKIP: $issueTitle (issue already exists)" -ForegroundColor DarkGray
        $skippedCount++
        continue
    }

    # Build issue body
    $body = @"
## E2E Test Failure

**Test:** ``$($failure.TestName)``
**Duration:** $($failure.Duration)

### Error Message
``````
$($failure.ErrorMessage)
``````

### Stack Trace
``````
$($failure.StackTrace)
``````

### Reproduction
``````powershell
`$env:NUGET_PACKAGES = "`$env:USERPROFILE\.nuget\packages2"
dotnet test tests/OpenClawNet.PlaywrightTests/ --filter "FullyQualifiedName~$($failure.TestName)"
``````

---
*Auto-generated by create-issues-from-failures.ps1*
"@

    if ($DryRun) {
        Write-Host "  DRY-RUN: Would create issue: $issueTitle" -ForegroundColor Yellow
    }
    else {
        $result = gh issue create --title "$issueTitle" --body "$body" --label "bug" --label "squad" --label "squad:ash" 2>&1
        if ($LASTEXITCODE -eq 0) {
            Write-Host "  CREATED: $issueTitle -> $result" -ForegroundColor Green
        }
        else {
            Write-Host "  ERROR creating issue: $result" -ForegroundColor Red
        }
    }
    $createdCount++
}

# Summary
Write-Host "`n========================================" -ForegroundColor Cyan
Write-Host " Summary" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "Tests run:      $totalTests"
Write-Host "Tests passed:   $passedCount" -ForegroundColor Green
Write-Host "Tests failed:   $failedCount" -ForegroundColor Red
Write-Host "Issues created: $createdCount" -ForegroundColor $(if ($DryRun) { "Yellow" } else { "Green" })
Write-Host "Issues skipped: $skippedCount" -ForegroundColor DarkGray
