using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.AI;
using Microsoft.Extensions.Logging;
using OpenClawNet.Skills;
using OpenClawNet.Storage;
using OpenClawNet.Storage.Entities;
using System.Diagnostics;

namespace OpenClawNet.Gateway.Services;

/// <summary>
/// Background service for synchronizing semantic vectors from embeddings into sqlite-vec storage.
/// Runs nightly to refresh the skill vector database with embeddings generated by Ollama.
/// </summary>
public sealed class SkillVectorSyncService
{
    private readonly IEmbeddingGenerator<string, Embedding<float>> _embeddingGenerator;
    private readonly IDbContextFactory<OpenClawDbContext> _dbContextFactory;
    private readonly ISkillsRegistry _skillsRegistry;
    private readonly ILogger<SkillVectorSyncService> _logger;

    public SkillVectorSyncService(
        IEmbeddingGenerator<string, Embedding<float>> embeddingGenerator,
        IDbContextFactory<OpenClawDbContext> dbContextFactory,
        ISkillsRegistry skillsRegistry,
        ILogger<SkillVectorSyncService> logger)
    {
        _embeddingGenerator = embeddingGenerator;
        _dbContextFactory = dbContextFactory;
        _skillsRegistry = skillsRegistry;
        _logger = logger;
    }

    /// <summary>
    /// Synchronizes skill vectors nightly by embedding skill descriptions and upserting into the database.
    /// Process is idempotent: safe to run multiple times without duplication.
    /// </summary>
    public async Task SyncSkillVectorsAsync(CancellationToken cancellationToken = default)
    {
        var sw = Stopwatch.StartNew();
        int totalSkills = 0;
        int successCount = 0;
        int failureCount = 0;
        int updatedCount = 0;
        int insertedCount = 0;

        try
        {
            await using var db = await _dbContextFactory.CreateDbContextAsync(cancellationToken);

            // Get all skills from the registry
            var snapshot = await _skillsRegistry.GetSnapshotAsync(cancellationToken);
            var skills = snapshot.Skills.ToList();

            totalSkills = skills.Count;
            _logger.LogInformation("Starting skill vector sync for {SkillCount} skills", totalSkills);

            if (totalSkills == 0)
            {
                _logger.LogInformation("No skills found to sync");
                return;
            }

            // Process skills in batches of 15 for efficiency
            const int batchSize = 15;
            for (int i = 0; i < skills.Count; i += batchSize)
            {
                var batch = skills.Skip(i).Take(batchSize).ToList();
                var descriptions = batch.Select(s => s.Description ?? s.Name).ToList();

                try
                {
                    // Generate embeddings for the batch
                    var embeddings = await _embeddingGenerator.GenerateAsync(
                        descriptions,
                        cancellationToken: cancellationToken);

                    // Upsert each embedding into the database
                    for (int j = 0; j < batch.Count && j < embeddings.Count; j++)
                    {
                        var skill = batch[j];
                        var embedding = embeddings[j];
                        var vectorBytes = ConvertEmbeddingToBytes(embedding.Vector.ToArray());

                        try
                        {
                            var existing = await db.SkillVectors
                                .AsNoTracking()
                                .FirstOrDefaultAsync(v => v.SkillName == skill.Name, cancellationToken);

                            if (existing != null)
                            {
                                // Update existing vector - keep CreatedAt unchanged
                                existing.Embedding = vectorBytes;
                                db.SkillVectors.Update(existing);
                                updatedCount++;
                            }
                            else
                            {
                                // Insert new vector
                                var skillVector = new SkillVector
                                {
                                    SkillName = skill.Name,
                                    Embedding = vectorBytes,
                                    CreatedAt = DateTime.UtcNow
                                };
                                db.SkillVectors.Add(skillVector);
                                insertedCount++;
                            }

                            successCount++;
                        }
                        catch (Exception ex)
                        {
                            failureCount++;
                            _logger.LogWarning(ex, "Failed to upsert vector for skill '{SkillName}'", skill.Name);
                        }
                    }

                    // Save batch to database
                    await db.SaveChangesAsync(cancellationToken);
                }
                catch (OperationCanceledException)
                {
                    throw;
                }
                catch (Exception ex)
                {
                    failureCount += batch.Count;
                    _logger.LogWarning(ex, "Failed to process batch of {BatchSize} skills, skipping batch", batch.Count);
                }
            }

            sw.Stop();
            _logger.LogInformation(
                "Skill vector sync completed: {SuccessCount} embedded, {FailureCount} failed, {UpdatedCount} updated, {InsertedCount} inserted in {ElapsedSeconds:F2}s",
                successCount, failureCount, updatedCount, insertedCount, sw.Elapsed.TotalSeconds);
        }
        catch (OperationCanceledException)
        {
            _logger.LogInformation("Skill vector sync cancelled");
            throw;
        }
        catch (Exception ex)
        {
            sw.Stop();
            _logger.LogError(ex, "Skill vector sync failed after {ElapsedSeconds:F2}s", sw.Elapsed.TotalSeconds);
            throw;
        }
    }

    /// <summary>
    /// Converts an embedding float array to bytes for storage.
    /// </summary>
    private static byte[] ConvertEmbeddingToBytes(float[] embedding)
    {
        var bytes = new byte[embedding.Length * sizeof(float)];
        Buffer.BlockCopy(embedding, 0, bytes, 0, bytes.Length);
        return bytes;
    }

    /// <summary>
    /// Converts bytes back to embedding float array for retrieval.
    /// </summary>
    public static float[] ConvertBytesToEmbedding(byte[] bytes)
    {
        var embedding = new float[bytes.Length / sizeof(float)];
        Buffer.BlockCopy(bytes, 0, embedding, 0, bytes.Length);
        return embedding;
    }
}
